[phases.setup]
nixPkgs = ['nodejs-18_x', 'python3', 'gcc']

[phases.install]
cmds = [
    'npm ci --include=dev',
]

[phases.build]
cmds = [
    'npm run build'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
